all: simple_cat better_cat ignore_pipe_exec
simple_cat:
	gcc -Wall simple_cat.c -o simple_cat
better_cat:
	gcc -Wall better_cat.c -o better_cat
ignore_pipe_exec:
	gcc -Wall ignore_pipe_exec.c -o ignore_pipe_exec
clean:
	rm -f simple_cat better_cat sigmask ignore_pipe_exec
